### ISSUE TITLE
Funhouse appears to only play 4 tones before running out of timers

### ISSUE THREAD

**Issue by DarcInc** [adafruit/Adafruit_CircuitPython_FunHouse#18] opened 2021-06-19 22:56 UTC
We were playing around with the Funhouse from our Ada Box using circuit python.  (We love it by the way).  It seems to only play 4 tones before throwing an exception that "all timers in use.".  The following snippet can be used to demonstrate the error.  Each button press plays one tone for one second.  Even if you wait several seconds between button pushes, it still throws the exception.  We're the latest circuit python 6.  

```python
from adafruit_funhouse import FunHouse
import time
funhouse = FunHouse(default_bg=None)

tones = [
    {'f' : 659, 'd' : 1},
    {'f' : 987, 'd' : 1},
    {'f' : 880, 'd' : 1},
    {'f' : 659, 'd' : 1},
    {'f' : 1000, 'd' : 1},
    {'f' : 700, 'd' : 1}
]

current = 0
while True: 
    if funhouse.peripherals.button_down : 
        t = tones[current]
        funhouse.peripherals.play_tone(t['f'], t['d'])
        current += 1
        if current == len(tones):
            current = 0
```

**Comment by tannewt** [comment] 2021-06-22 00:45
@makermelissa My guess would be that the library isn't releasing the timer.

@DarcInc What version of CircuitPython are you running this on? There is a chance that it's an internal bug.

**Comment by makermelissa** [comment] 2021-06-22 15:05
That's certainly possible. I didn't realize it needed to release anything.

**Comment by makermelissa** [comment] 2021-07-19 16:44
I was able to reproduce the issue with both CircuitPython 6.3 and 7.0. The FunHouse library directly calls simpleio's tone() function. It's in a weird while loop thing, but even with that bit commented out, the issue still occurs, so I don't think the issue is in the FunHouse library. I even explicitly tried adding a deinit() call to simpleio and it still held onto the timers, so I am leaning towards this being an internal bug at this point.

@tannewt should I transfer the issue or create a new one on the main CircuitPython repo?

**Comment by tannewt** [comment] 2021-07-20 01:09
@makermelissa Please test with absolute latest because I think it was fixed by https://github.com/adafruit/circuitpython/pull/4999 and transfer if it is still an issue. Thanks!

**Comment by makermelissa** [comment] 2021-07-20 02:07
Absolute latest worked. Closing this issue because it was fixed by https://github.com/adafruit/circuitpython/pull/4999.

**Closed as completed by makermelissa** 2021-07-20 02:07 UTC
